In [114]:
import pandas as pd
import matplotlib.pyplot as plt

In [115]:
df = pd.read_csv("data/properties.csv")
df.head()

,property_id,title,district,city,property_type,price_eur,size_sqm,bedrooms,bathrooms,floor,...,furnished,terrace,elevator,parking,heating,nearby_transport,description,inspection_notes,legal_notes,features
0,P001,Two-Bedroom Apartment in Lozenets Near Metro,Lozenets,Sofia,apartment,118000,78,2,1,4,...,partly furnished,True,True,False,central heating,"James Bourchier metro station, about 5 minutes...",This bright two-bedroom apartment is located o...,The apartment is in very good condition. Kitch...,Ownership documents reviewed. Act 16 is availa...,"terrace, equipped kitchen, secure entrance, ne..."
1,P002,One-Bedroom Apartment in Mladost 1 Close to Metro,Mladost 1,Sofia,apartment,99000,65,1,1,5,...,furnished,True,True,False,district heating,"Mladost 1 metro station, bus lines, and easy a...",Comfortable one-bedroom apartment in Mladost 1...,The apartment is generally well kept. Kitchen ...,Seller states that title is clean. Basic owner...,"balcony, furnished, elevator, metro access, pr..."
2,P003,Modern Studio in Studentski Grad for Investment,Studentski Grad,Sofia,studio,87000,54,0,1,3,...,fully furnished,True,True,False,air conditioning,Bus routes to city center and university areas,"Modern studio apartment in Studentski Grad, po...",The apartment is freshly painted and the furni...,Act 16 available. Ownership history appears st...,"balcony, fully furnished, investment potential..."
3,P004,Spacious Apartment in Vitosha District with Mo...,Vitosha,Sofia,apartment,145000,96,2,2,4,...,partly furnished,True,True,True,gas heating,Bus connections to Paradise Center and central...,Large two-bedroom apartment in Vitosha distric...,The apartment is in excellent condition with m...,Property registration is complete and the sell...,"mountain view, terrace, parking, new building,..."
4,P005,Central Sofia Apartment Near Serdika Metro,Center,Sofia,apartment,165000,92,2,1,2,...,unfurnished,False,False,False,central heating,"Serdika metro station, tram and bus lines, cen...",Apartment in the historic central area of Sofi...,The apartment is structurally sound but would ...,Ownership has been verified based on the docum...,"central location, high ceilings, brick buildin..."

In [116]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   property_id       50 non-null     str
 1   title             50 non-null     str
 2   district          50 non-null     str
 3   city              50 non-null     str
 4   property_type     50 non-null     str
 5   price_eur         50 non-null     int64
 6   size_sqm          50 non-null     int64
 7   bedrooms          50 non-null     int64
 8   bathrooms         50 non-null     int64
 9   floor             50 non-null     int64
 10  total_floors      50 non-null     int64
 11  year_built        50 non-null     int64
 12  condition         50 non-null     str
 13  furnished         50 non-null     str
 14  terrace           50 non-null     bool
 15  elevator          50 non-null     bool
 16  parking           50 non-null     bool
 17  heating           50 non-null     str
 18  nearby_transport  50 non-null     str
 19  description       50 non-null     str
 20  inspection_notes  50 non-null     str
 21  legal_notes       50 non-null     str
 22  features          50 non-null     str
dtypes: bool(3), int64(7), str(13)
memory usage: 38.8 KB

In [117]:
df = df.drop(columns=["property_id", "title", "description", "inspection_notes", "legal_notes", "features", "nearby_transport", "city"])
df.head()

,district,property_type,price_eur,size_sqm,bedrooms,bathrooms,floor,total_floors,year_built,condition,furnished,terrace,elevator,parking,heating
0,Lozenets,apartment,118000,78,2,1,4,6,2008,very good,partly furnished,True,True,False,central heating
1,Mladost 1,apartment,99000,65,1,1,5,8,1986,good,furnished,True,True,False,district heating
2,Studentski Grad,studio,87000,54,0,1,3,6,2015,very good,fully furnished,True,True,False,air conditioning
3,Vitosha,apartment,145000,96,2,2,4,5,2018,excellent,partly furnished,True,True,True,gas heating
4,Center,apartment,165000,92,2,1,2,4,1962,needs cosmetic renovation,unfurnished,False,False,False,central heating

In [118]:
from sklearn.preprocessing import OneHotEncoder

categorical_cols = [
    "district",
    "property_type",
    "condition",
    "furnished",
    "heating",
    "terrace",
    "elevator",
    "parking"
]

encoder = OneHotEncoder(sparse_output=False)

encoded_features = encoder.fit_transform(df[categorical_cols])

encoded_df = pd.DataFrame(
    encoded_features,
    columns=encoder.get_feature_names_out(categorical_cols),
    index=df.index
)

df = pd.concat([df.drop(columns=categorical_cols), encoded_df], axis=1)

df.head()

,price_eur,size_sqm,bedrooms,bathrooms,floor,total_floors,year_built,district_Banishora,district_Bankya,district_Boyana,...,heating_district heating,heating_gas heating,heating_local heating,heating_local heating system,terrace_False,terrace_True,elevator_False,elevator_True,parking_False,parking_True
0,118000,78,2,1,4,6,2008,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1,99000,65,1,1,5,8,1986,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,87000,54,0,1,3,6,2015,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
3,145000,96,2,2,4,5,2018,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,165000,92,2,1,2,4,1962,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [119]:
from sklearn.model_selection import train_test_split

X = df.drop("price_eur", axis=1)
y = df["price_eur"]

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )

X_train = X.iloc[:-10]
X_test  = X.iloc[-10:]

y_train = y.iloc[:-10]
y_test  = y.iloc[-10:]

X_test.head()

,size_sqm,bedrooms,bathrooms,floor,total_floors,year_built,district_Banishora,district_Bankya,district_Boyana,district_Center,...,heating_district heating,heating_gas heating,heating_local heating,heating_local heating system,terrace_False,terrace_True,elevator_False,elevator_True,parking_False,parking_True
40,97,2,2,3,5,2019,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
41,90,2,1,4,6,2018,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
42,80,2,1,3,6,2005,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
43,73,1,1,6,8,1998,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
44,115,3,2,4,6,2016,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

In [120]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)
rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
rf_r2 = r2_score(y_test, rf_predictions)

print("MAE:", rf_mae)
print("RMSE:", rf_rmse)
print("R2:", rf_r2)

MAE: 10788.0
RMSE: 21688.210737633475
R2: 0.8651190341691136

In [121]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6
)

xgb_model.fit(X_train, y_train)

xgb_predictions = xgb_model.predict(X_test)
xgb_mae = mean_absolute_error(y_test, xgb_predictions)
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_predictions))
xgb_r2 = r2_score(y_test, xgb_predictions)

print("MAE:", xgb_mae)
print("RMSE:", xgb_rmse)
print("R2:", xgb_r2)

MAE: 10872.365234375
RMSE: 19377.732375074233
R2: 0.8923264145851135

In [122]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(
    rf_model,
    X,
    y,
    cv=5,
    scoring="neg_mean_absolute_error"
)

mae_cv = np.mean(np.abs(scores))

print("Cross-validated MAE:", mae_cv)

Cross-validated MAE: 10355.183333333334

The better model for this small dataset is Random Forest

In [123]:
# pick the property to auction
property_row = df.iloc[42]
X_property = property_row.drop("price_eur").to_frame().T
predicted_price = rf_model.predict(X_property)

print("Predicted price:", predicted_price[0])

Predicted price: 118075.0

In [124]:
import joblib

joblib.dump(rf_model, "rf_property_model.pkl")
joblib.dump(encoder, "rf_encoder.pkl")

['rf_encoder.pkl']